version: '3.7'

services:

    #PHP Service
    app:
        build:
            args:
                user: zentcode
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: subscriptions-backend-php
        container_name: subscriptions-backend-php-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - subscriptions

    #MySQL Service
    db:
        image: mysql:8.0
        container_name: subscriptions-backend-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        ports:
            - 8001:3306
        networks:
            - subscriptions

    #NGINX Service
    nginx:
        image: nginx:1.17-alpine
        container_name: subscriptions-backend-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - subscriptions

networks:
    subscriptions:
        driver: bridge
